language: node_js
node_js:
  - "8.9.3"

cache:
  directories:
    - "node_modules"

addons:
  chrome: stable
  firefox: latest

before_install:
  - npm install -g gulp karma

install:
  - npm install

before_script:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3